version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sensor_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensors
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend-python
    container_name: sensor_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend-python:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db_data: