services:
  db:
    image: postgres:15
    container_name: sensor_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-sensors}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-sensors}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend-python
    container_name: backend_python
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend-python:/code
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-sensors}
      DB_PORT: "5432"
    depends_on:
      - db

volumes:
  db_data:
